# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 07:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0002_auto_20160918_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 9, 18, 7, 52, 0, 407747))),
                ('title', models.CharField(default='', max_length=100)),
                ('proportion', models.IntegerField(default=0)),
            ],
        ),
    ]
