# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 08:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0004_auto_20160918_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 18, 8, 39, 53, 353805)),
        ),
    ]
