# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0005_auto_20160918_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='date',
        ),
    ]
