# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0006_remove_vote_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='created_it',
            field=models.TimeField(default=datetime.datetime(2016, 9, 18, 9, 40, 51, 117604)),
        ),
    ]
