# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 14:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0007_vote_created_it'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_it',
            field=models.TimeField(default=datetime.datetime(2016, 9, 18, 14, 15, 47, 524134)),
        ),
    ]
