# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-24 14:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0008_auto_20160918_1415'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='restaurant_list',
            new_name='RestaurantList',
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_it',
            field=models.TimeField(default=datetime.datetime(2016, 9, 24, 14, 39, 37, 873453)),
        ),
    ]
