# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-24 14:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0010_auto_20160924_1440'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='restaurant_list',
            new_name='RestaurantList',
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_it',
            field=models.TimeField(default=datetime.datetime(2016, 9, 24, 14, 44, 8, 684353)),
        ),
    ]
