# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-26 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0013_vote_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('proportion', models.IntegerField(default=0)),
            ],
        ),
    ]
