# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-26 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0014_predictpopulation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PredictPopulation',
            new_name='PredictProportion',
        ),
    ]
