# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-26 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0015_auto_20170126_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PredictProportion',
            new_name='PredictedProportion',
        ),
    ]
