# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-26 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0017_auto_20170126_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='sex',
            field=models.CharField(default='', max_length=6),
        ),
    ]
