# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-05 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0018_auto_20170126_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='bob', max_length=100)),
            ],
        ),
    ]
