# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0019_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='bob', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('latitude', models.CharField(default='', max_length=20)),
                ('longitude', models.CharField(default='', max_length=20)),
                ('menu', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='RestaurantList',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='age',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='sex',
        ),
    ]
