# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0020_auto_20170723_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.CharField(blank=True, default='', max_length=3000),
        ),
    ]
